# Site settings
title: jaisonv
header-img: img/home-bg.jpg

description: "Jaison's personal website about programming stuff"
baseurl: ""
url: "http://jaisonv.com"

email: jaisonnvieira@gmail.com
twitter_username: jaisonnvieira
github_username:  jaisonv
linkedin_username:  jaisonvieira

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", contact.html, CNAME]
