# Site settings
title: jaisonv
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Meta description here!"
baseurl: ""
url: "http://jaisonv.com"
twitter_username: jaisonnvieira
github_username:  jaisonv
linkedin_username:  jaisonvieira

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
